### ISSUE TITLE
Strange error...

### ISSUE THREAD

**Issue by gefero** [Marcnuth/AnomalyDetection#2]
Strange error... 

![image](https://user-images.githubusercontent.com/10410987/37260969-4bff5eca-2577-11e8-8c16-724b707dd082.png)

**Comment by hokiegeek2** [comment]
I fixed this in my pull request

**Comment by hokiegeek2** [comment]
@gefero if you are still interested, please checkout and confirm you are cool with this fix.

**Comment by Marcnuth** [comment]
close this after @hokiegeek2  fix it.
