### ISSUE TITLE
A bug in test_detect_ts.py

### ISSUE THREAD

**Issue by vnnw** [Marcnuth/AnomalyDetection#27]
In line https://github.com/Marcnuth/AnomalyDetection/blob/2759feac6f8167f2670b59f0148f39726117ed46/tests/test_detect_ts.py#L6

The 'get_data_tuple' should be '_get_data_tuple' instead.

**Comment by Marcnuth** [comment]
thanks

this is fixed by @lbl1985   in https://github.com/Marcnuth/AnomalyDetection/pull/25
