### ISSUE TITLE
ModuleNotFoundError: No module named tad

### ISSUE THREAD

**Issue by zkid18** [Marcnuth/AnomalyDetection#28]
After [commit](https://github.com/Marcnuth/AnomalyDetection/commit/efbc4e1f27f82727f4f25d8725ffe16604cb6b76) `efbc4e1f27f82727f4f25d8725ffe16604cb6b76` I have problems with importing the library. 

`pip3 install tad`
`import tad`
`>ModuleNotFoundError: No module named tad`

**Comment by mateusccoelho** [comment]
I had the same problem, but solved this issue removing line 9 of __init__.py, in which the variable __name__ is specified. In my case, after I installed the package, I went to the installation folder and made this change there. I guess you can also download the repo, edit the source code and then install it. The result would be the same.

**Comment by Marcnuth** [comment]
fixed in latest version.

**Comment by ErinKnochenhauer** [comment]
Hi Marc, I am seeing the same import issue. 
pip3 install tad
import tad
ModuleNotFoundError: No module named 'tad'
