### ISSUE TITLE
Plot=True referenced before assignment

### ISSUE THREAD

**Issue by dr1911** [Marcnuth/AnomalyDetection#3]
When we call with "Plot=True" parameter, like this:
`data_ = pd.read_csv('analytics_test.csv',
                    index_col='timestamp',
                    parse_dates=True,
                    squeeze=True,
                    date_parser=dparserfunc)
`

returns this error:
`UnboundLocalError: local variable 'num_days_per_line' referenced before assignment`

in anomaly_detect_ts.py file in 274. line:
`
...
    if plot:
        num_days_per_line
        breaks
        x_subset_week
...
`

**Comment by hokiegeek2** [comment]
Saw this as well

**Comment by Marcnuth** [comment]
close this thanks for the fix by @hokiegeek2
